(()=>{'use strict';
const service=document.querySelector('.service-journey'),stage=service.querySelector('.service-stage'),slides=[...document.querySelectorAll('.service-slides article')],brands=document.querySelector('.brand-journey'),space=document.querySelector('.brand-space'),caption=document.querySelector('.brand-caption'),allWork=document.querySelector('#all-work'),about=document.querySelector('#about'),choices=document.querySelector('.choice-section');
const items=window.kenPortfolioItems||[];const planes=items.map(([id,title],i)=>{const plane=document.createElement('div');plane.className='brand-plane';const image=document.createElement('img');image.src='assets/portfolio/'+id+'.png';image.alt='';image.decoding='async';plane.append(image);space.append(plane);return plane;});
const canvas=document.querySelector('.spatial-field'),ctx=canvas.getContext('2d');let w=0,h=0,raf=0,active=false,smoothed=0,last=0;
const clamp=x=>Math.max(0,Math.min(1,x)),smooth=(a,b,x)=>{const t=clamp((x-a)/(b-a));return t*t*(3-2*t);};
const nav=()=>document.querySelector('.nav').offsetHeight;const progress=el=>clamp((nav()-el.getBoundingClientRect().top)/Math.max(1,el.offsetHeight-(innerHeight-nav())));
function measure(){w=stage.clientWidth;h=stage.clientHeight;const d=Math.min(devicePixelRatio||1,1.5);canvas.width=w*d;canvas.height=h*d;if(ctx)ctx.setTransform(d,0,0,d,0,0);update();}
function field(p){if(!ctx)return;ctx.clearRect(0,0,w,h);const horizon=h*.43;for(let zi=0;zi<30;zi++){const depth=1+(zi+(p*28)%1)*.21;const scale=1/depth;for(let xi=-28;xi<=28;xi++){const x=w/2+xi*42*scale;const wave=Math.sin(xi*.23+zi*.22+p*5)*22+Math.sin(zi*.34+p*4)*30;const y=horizon+(h*.65+wave)*scale;ctx.fillStyle='rgba(138,209,170,'+(.12+scale*.38)+')';ctx.beginPath();ctx.arc(x,y,.5+scale*1.4,0,6.28);ctx.fill();}}}
function update(){const reduced=document.body.classList.contains('reduced'),sp=progress(service),bp=progress(brands);if(reduced){slides.forEach(s=>{s.style.opacity=1;s.style.visibility='visible';s.style.transform='none';s.removeAttribute('aria-hidden');});allWork.open=true;field(0);}else{const phase=sp*3;slides.forEach((el,i)=>{const local=phase-i;const entrance=i===0?1:smooth(-.20,.08,local),exit=i===2?1:1-smooth(.78,1.01,local),opacity=entrance*exit;el.style.opacity=opacity;el.style.visibility=opacity<.01?'hidden':'visible';el.style.transform='translate3d('+((1-entrance)*45-(1-exit)*30)+'px,'+((1-entrance)*75-(1-exit)*65)+'px,'+(-150*(1-entrance)-100*(1-exit))+'px)';el.setAttribute('aria-hidden',String(opacity<.1));});field(sp);}
service.querySelector('.service-track i').style.transform='scaleX('+sp+')';stage.dataset.scVerifyState='service:'+sp.toFixed(3);stage.dataset.scVerifyHold=String(reduced);
const mobile=innerWidth<=700,travel=(items.length-1)*650+2900;
planes.forEach((plane,i)=>{const z=-2000-i*650+bp*travel;const alpha=smooth(-2500,-1350,z)*(1-smooth(mobile?450:600,mobile?620:790,z));const side=i%2===0?-1:1;const x=side*(mobile?118:260),y=((i%3)-1)*(mobile?42:65);plane.style.transform='translate3d('+x+'px,'+y+'px,'+z+'px) rotateY('+(side*-13)+'deg) rotateZ('+(side*3)+'deg)';plane.style.opacity=alpha;plane.style.visibility=alpha<.01?'hidden':'visible';});
const selected=Math.min(items.length-1,Math.max(0,Math.round((bp*travel-2000)/650)));caption.textContent=items[selected]?items[selected][1]:'';brands.querySelector('.brand-stage').dataset.scVerifyState='camera:'+(bp*travel).toFixed(1);brands.querySelector('.brand-stage').dataset.scVerifyHold=String(reduced);
const a=about.getBoundingClientRect(),c=choices.getBoundingClientRect();about.style.setProperty('--portrait-shift',reduced?'0px':Math.max(-24,Math.min(24,a.top*.045))+'px');const cp=clamp((innerHeight-c.top)/(innerHeight+c.height));choices.style.setProperty('--hand-shift',reduced?'0px':(25-cp*45)+'px');choices.style.setProperty('--card-shift',reduced?'0px':(12-cp*28)+'px');}
function tick(now){raf=0;update();if(active&&!document.hidden&&!document.body.classList.contains('reduced'))raf=requestAnimationFrame(tick);}
function schedule(){if(!raf&&!document.hidden)raf=requestAnimationFrame(tick);}
addEventListener('scroll',schedule,{passive:true});addEventListener('resize',measure);document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;}else schedule();});new IntersectionObserver(entries=>{active=entries[0].isIntersecting;schedule();}).observe(service);new MutationObserver(schedule).observe(document.body,{attributes:true,attributeFilter:['class']});
document.querySelector('.gallery-jump').addEventListener('click',()=>{allWork.open=true;});measure();
})();
